services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: froshy_backend_prod
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: froshy_frontend_prod
    ports:
      - "3000:3000"
    env_file:
      - .env.production

  db:
    image: postgres:15
    container_name: froshy_db_prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_prod:
