version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: froshy_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: froshy_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15
    container_name: froshy_db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: frosy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  frontend_node_modules:
