services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: froshy_backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env.development
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: froshy_frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    env_file:
      - .env.development
    command: npm run dev

  db:
    image: postgres:15
    container_name: froshy_db_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  frontend_node_modules:
