services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: froshy_backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env.development
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: froshy_frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    env_file:
      - .env.development
    command: npm run dev

  db:
    image: postgres:16-alpine
    container_name: froshy_db_dev
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  frontend_node_modules:
